const AGORA_API_BASE_URL = 'http://localhost:8090'

const USER_ENDPOINT = '/user'
const AUTHENTICATION_ENDPOINT = '/authentication'

export { AGORA_API_BASE_URL, USER_ENDPOINT, AUTHENTICATION_ENDPOINT }
